
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: pipelines-javascript-docker
  Docker_BUILDKIT: 1

steps:
- task: Docker@2
  displayName: 'Build an Image'
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
